### ISSUE TITLE
Warning When Activating Template

### ISSUE THREAD

**Issue by ghost** [studiorabota/sage-twig-theme#10]
I get the following (very long) warning when I activate the template and check out the home page:

---

Warning: post.permalink has been removed, please use post.link in C:\wamp64\www\timber\wp-content\plugins\timber-library\lib\Helper.php on line 201 Call Stack #TimeMemoryFunctionLocation 10.0014236592{main}( )...\index.php:0 20.0021239664require( 'C:\wamp64\www\timber\wp-blog-header.php' )...\index.php:17 30.297221901768require_once( 'C:\wamp64\www\timber\wp-includes\template-loader.php' )...\wp-blog-header.php:19 40.315722296872include( 'C:\wamp64\www\timber\wp-content\themes\timber-sage\index.php' )...\template-loader.php:75 50.349122414440Timber\Timber::render( )...\index.php:4 60.349122414640Timber\Timber::fetch( )...\Timber.php:296 70.349122414840Timber\Timber::compile( )...\Timber.php:281 80.351022422752Timber\Loader->render( )...\Timber.php:245 90.393023375968Twig_Environment->render( )...\Loader.php:71 100.524725563368Twig_Template->render( )...\Environment.php:347 110.524725580080Twig_Template->display( )...\Template.php:366 120.524925581248Twig_Template->displayWithErrorHandling( )...\Template.php:355 130.524925581320__TwigTemplate_e555d46274f6b65e7debc4b8da4a5f78deb5350b3903117fd8e322f28bf29cbd->doDisplay( )...\Template.php:381 140.524925581792Twig_Template->display( )...\Environment.php(403) : eval()'d code:25 150.524925582368Twig_Template->displayWithErrorHandling( )...\Template.php:355 160.524925582624__TwigTemplate_777b329bd357055660f880db23249e2699ade3ffea5f640be33f51dcdb6d9531->doDisplay( )...\Template.php:381 170.564125734192Twig_Template->displayBlock( )...\Environment.php(403) : eval()'d code:47 180.564125734424__TwigTemplate_e555d46274f6b65e7debc4b8da4a5f78deb5350b3903117fd8e322f28bf29cbd->block_content( )...\Template.php:167 190.575825727808Twig_Template->display( )...\Environment.php(403) : eval()'d code:55 200.575825728256Twig_Template->displayWithErrorHandling( )...\Template.php:355 210.575825728376__TwigTemplate_75fbb7333eafd17e54f40d366facfca2a0c1c10a7beb35b45d166b8195f973ab->doDisplay( )...\Template.php:381 220.578025729576Twig_Template->getAttribute( )...\Environment.php(403) : eval()'d code:26 230.578125742432call_user_func_array:{C:\wamp64\www\timber\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\Template.php:598} ( )...\Template.php:598 240.578125742640Timber\Post->permalink( )...\Template.php:598 250.578125742792Timber\Helper::warn( )...\Post.php:1348 260.578125742888trigger_error ( )...\Helper.php:201 http://localhost/timber/2016/05/11/hello-world/">Hello world!

---

Any idea what this is about and how to fix it?

Thanks.

**Comment by studiorabota** [comment]
Thanks @moshemo and sorry for my late reply. I merged your fix #11. Thanks!
