### ISSUE TITLE
post object in header

### ISSUE THREAD

**Issue by maxvanloosbroek** [studiorabota/sage-twig-theme#8]
Hi there,

I'd like to thank you for this theme as it saves me a lot of time with my theme development. I've run into an issue however, I cannot access my post object in the header.twig file. For instance {{post.title}} doesn't work and I can't seem to figure out why or I'd have changed it. Am I missing something here or is this intentional behavior.

Thanks again for your time and effort!

**Comment by studiorabota** [comment]
Hi @januarian ,

Great to hear it saved you time!

Standard the post object is not available, only the post**s** with an 's'. 

You can wrap it in a posts loop:

```
    {% for post in posts %}
            <h1>{{ post.title }}</h1>
    {% endfor %}
```

Or my preferred way is to make it available via lib/timber.php in add_to_context():

```
if (is_singular()) {
    $context['post'] = new TimberPost();
}
```

You can also do this per .php file. For ex: page.php.

```
$data = Timber::get_context();
$data['post'] = new TimberPost();
Timber::render('templates/page.twig', $data);
```

**Sidenote:** Placing the post.title in header.twig sounds strange do. Header.twig is normally also for archive, home, and all your other non-singular templates which do not have a post.title.

**Comment by studiorabota** [comment]
Hi @januarian , I'm closing the issue. Let me know if the answer above was not sufficient.

**Comment by maxvanloosbroek** [comment]
Sorry for commenting so late, thanks for the support! Those are excellent solutions for what I want, I decided to set up the post in the php files where needed. 
Although it might not be according to convention, in this case all pages actually have a page title which is used in the header. It's not really a classical blog website.
